### ISSUE TITLE
 nuxtCtx.set is not a function

### ISSUE THREAD

**Issue by podlebar** [harlan-zw/nuxt-webpack-optimisations#38]
**Describe the bug**
After a clean installation of this module i get following error when starting up:
 nuxtCtx.set is not a function

**To Reproduce**
follow instruction in the readme

**Expected behavior**
dev server start works
**Screenshots**
<img width="1006" alt="Bildschirmfoto 2022-01-13 um 10 09 42" src="https://user-images.githubusercontent.com/342104/149300013-b023c2df-1235-4554-bc0e-e01d9f11f248.png">

**Comment by harlan-zw** [comment]
I think this was a bug with an early version of @nuxt/kit, using the latest v2 nuxt and version of this package I can't replicate.

Please re-open with a reproduction if it's still an issue (and sorry for the delay in response).
