### ISSUE TITLE
Can i disabled this module in dev mode ?

### ISSUE THREAD

**Issue by nasirDoe** [harlan-zw/nuxt-webpack-optimisations#39]
**Is your feature request related to a problem? Please describe.**
Because when i ran in dev mode, my site is broken.

<img width="822" alt="Screen Shot 2022-02-21 at 09 30 27" src="https://user-images.githubusercontent.com/16643567/154879384-e49abad3-29ec-4a5e-92e9-e2c2cc31772b.png">

Thanks

**Comment by harlan-zw** [comment]
Hey @nasirDoe 

Each optimisation can be disabled conditionally. It may be worth going through the features and seeing which one is breaking the site. Seems like it could be the postcss one

```ts
export default {
  webpackOptimisations: {
    features: {
      // this could fix it 
      postcssNoPolyfills: false,
      // change true to false for each one until things start working
      esbuildLoader: true,
      esbuildMinifier: true,
      imageFileLoader: true,
      webpackOptimisations: true,
      cacheLoader: true,
      hardSourcePlugin: false,
      parallelPlugin: false,
    }
  }
}
```

Otherwise to have optimisations only work in dev you can see the example in the read me.

```ts
 webpackOptimisations: {
    // hard source is the riskiest, if you have issues don't enable it
    hardSourcePlugin: process.env.NODE_ENV === 'development',
    parallelPlugin: process.env.NODE_ENV === 'development',
  }
```

**Comment by nasirDoe** [comment]
thanks @harlan-zw for your question. it's helps
